"""add prompts and prompt_versions tables

Revision ID: 17e931a93b99
Revises: b9d2d9166639
Create Date: 2025-11-28 21:48:46.144807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17e931a93b99'
down_revision = 'b9d2d9166639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="Unique identifier for code usage (e.g., 'email_summarizer')"),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_slug'), 'prompts', ['slug'], unique=True)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('commit_message', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Only one version per prompt should be active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_thread_seq', 'messages', ['thread_id', 'sequence_num'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LiteLLM_OrganizationTable',
    sa.Column('organization_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('organization_alias', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('budget_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('models', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('model_spend', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('object_permission_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['LiteLLM_BudgetTable.budget_id'], name='LiteLLM_OrganizationTable_budget_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['object_permission_id'], ['LiteLLM_ObjectPermissionTable.object_permission_id'], name='LiteLLM_OrganizationTable_object_permission_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('organization_id', name='LiteLLM_OrganizationTable_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('LiteLLM_DailyTagSpend',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_llm_provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_read_input_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_creation_input_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('api_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('successful_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('LiteLLM_DailyTagSpend_pkey'))
    )
    op.create_index(op.f('LiteLLM_DailyTagSpend_tag_idx'), 'LiteLLM_DailyTagSpend', ['tag'], unique=False)
    op.create_index(op.f('LiteLLM_DailyTagSpend_tag_date_api_key_model_custom_llm_pro_key'), 'LiteLLM_DailyTagSpend', ['tag', 'date', 'api_key', 'model', 'custom_llm_provider'], unique=True)
    op.create_index(op.f('LiteLLM_DailyTagSpend_model_idx'), 'LiteLLM_DailyTagSpend', ['model'], unique=False)
    op.create_index(op.f('LiteLLM_DailyTagSpend_date_idx'), 'LiteLLM_DailyTagSpend', ['date'], unique=False)
    op.create_index(op.f('LiteLLM_DailyTagSpend_api_key_idx'), 'LiteLLM_DailyTagSpend', ['api_key'], unique=False)
    op.create_table('LiteLLM_EndUserTable',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('allowed_model_region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['LiteLLM_BudgetTable.budget_id'], name=op.f('LiteLLM_EndUserTable_budget_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('LiteLLM_EndUserTable_pkey'))
    )
    op.create_table('LiteLLM_ProxyModelTable',
    sa.Column('model_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('litellm_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('model_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('model_id', name=op.f('LiteLLM_ProxyModelTable_pkey'))
    )
    op.create_table('LiteLLM_DailyUserSpend',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_llm_provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_read_input_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_creation_input_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('api_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('successful_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('LiteLLM_DailyUserSpend_pkey'))
    )
    op.create_index(op.f('LiteLLM_DailyUserSpend_user_id_idx'), 'LiteLLM_DailyUserSpend', ['user_id'], unique=False)
    op.create_index(op.f('LiteLLM_DailyUserSpend_user_id_date_api_key_model_custom_ll_key'), 'LiteLLM_DailyUserSpend', ['user_id', 'date', 'api_key', 'model', 'custom_llm_provider'], unique=True)
    op.create_index(op.f('LiteLLM_DailyUserSpend_model_idx'), 'LiteLLM_DailyUserSpend', ['model'], unique=False)
    op.create_index(op.f('LiteLLM_DailyUserSpend_date_idx'), 'LiteLLM_DailyUserSpend', ['date'], unique=False)
    op.create_index(op.f('LiteLLM_DailyUserSpend_api_key_idx'), 'LiteLLM_DailyUserSpend', ['api_key'], unique=False)
    op.create_table('LiteLLM_UserNotifications',
    sa.Column('request_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('models', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('request_id', name=op.f('LiteLLM_UserNotifications_pkey'))
    )
    op.create_table('LiteLLM_CronJob',
    sa.Column('cronjob_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pod_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='JobStatus'), server_default=sa.text('\'INACTIVE\'::"JobStatus"'), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('ttl', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('cronjob_id', name=op.f('LiteLLM_CronJob_pkey'))
    )
    op.create_table('LiteLLM_BudgetTable',
    sa.Column('budget_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('max_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('soft_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_parallel_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('model_max_budget', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('budget_duration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget_reset_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('budget_id', name='LiteLLM_BudgetTable_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('LiteLLM_AuditLog',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('changed_by_api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('LiteLLM_AuditLog_pkey'))
    )
    op.create_table('LiteLLM_ManagedVectorStoresTable',
    sa.Column('vector_store_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('custom_llm_provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector_store_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector_store_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector_store_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('litellm_credential_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vector_store_id', name=op.f('LiteLLM_ManagedVectorStoresTable_pkey'))
    )
    op.create_table('LiteLLM_HealthCheckTable',
    sa.Column('health_check_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('healthy_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unhealthy_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('checked_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('health_check_id', name=op.f('LiteLLM_HealthCheckTable_pkey'))
    )
    op.create_index(op.f('LiteLLM_HealthCheckTable_status_idx'), 'LiteLLM_HealthCheckTable', ['status'], unique=False)
    op.create_index(op.f('LiteLLM_HealthCheckTable_model_name_idx'), 'LiteLLM_HealthCheckTable', ['model_name'], unique=False)
    op.create_index(op.f('LiteLLM_HealthCheckTable_checked_at_idx'), 'LiteLLM_HealthCheckTable', ['checked_at'], unique=False)
    op.create_table('LiteLLM_GuardrailsTable',
    sa.Column('guardrail_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('guardrail_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('litellm_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('guardrail_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('guardrail_id', name=op.f('LiteLLM_GuardrailsTable_pkey'))
    )
    op.create_index(op.f('LiteLLM_GuardrailsTable_guardrail_name_key'), 'LiteLLM_GuardrailsTable', ['guardrail_name'], unique=True)
    op.create_table('LiteLLM_InvitationLink',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_accepted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['LiteLLM_UserTable.user_id'], name=op.f('LiteLLM_InvitationLink_created_by_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['LiteLLM_UserTable.user_id'], name=op.f('LiteLLM_InvitationLink_updated_by_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['LiteLLM_UserTable.user_id'], name=op.f('LiteLLM_InvitationLink_user_id_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('LiteLLM_InvitationLink_pkey'))
    )
    op.create_table('LiteLLM_ErrorLogs',
    sa.Column('request_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('startTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('endTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('api_base', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('model_group', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('litellm_model_name', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('request_kwargs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('exception_string', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('request_id', name=op.f('LiteLLM_ErrorLogs_pkey'))
    )
    op.create_table('LiteLLM_ObjectPermissionTable',
    sa.Column('object_permission_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mcp_servers', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('vector_stores', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('object_permission_id', name='LiteLLM_ObjectPermissionTable_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('LiteLLM_ModelTable',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"LiteLLM_ModelTable_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='LiteLLM_ModelTable_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('LiteLLM_TeamMembership',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('budget_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['LiteLLM_BudgetTable.budget_id'], name=op.f('LiteLLM_TeamMembership_budget_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', 'team_id', name=op.f('LiteLLM_TeamMembership_pkey'))
    )
    op.create_table('LiteLLM_DailyTeamSpend',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_llm_provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_read_input_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cache_creation_input_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('api_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('successful_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('LiteLLM_DailyTeamSpend_pkey'))
    )
    op.create_index(op.f('LiteLLM_DailyTeamSpend_team_id_idx'), 'LiteLLM_DailyTeamSpend', ['team_id'], unique=False)
    op.create_index(op.f('LiteLLM_DailyTeamSpend_team_id_date_api_key_model_custom_ll_key'), 'LiteLLM_DailyTeamSpend', ['team_id', 'date', 'api_key', 'model', 'custom_llm_provider'], unique=True)
    op.create_index(op.f('LiteLLM_DailyTeamSpend_model_idx'), 'LiteLLM_DailyTeamSpend', ['model'], unique=False)
    op.create_index(op.f('LiteLLM_DailyTeamSpend_date_idx'), 'LiteLLM_DailyTeamSpend', ['date'], unique=False)
    op.create_index(op.f('LiteLLM_DailyTeamSpend_api_key_idx'), 'LiteLLM_DailyTeamSpend', ['api_key'], unique=False)
    op.create_table('LiteLLM_SpendLogs',
    sa.Column('request_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('call_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('startTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('endTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('completionStartTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('model_group', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('custom_llm_provider', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('api_base', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('user', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('cache_hit', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('cache_key', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('request_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('end_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requester_ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proxy_server_request', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('request_id', name=op.f('LiteLLM_SpendLogs_pkey'))
    )
    op.create_index(op.f('LiteLLM_SpendLogs_startTime_idx'), 'LiteLLM_SpendLogs', ['startTime'], unique=False)
    op.create_index(op.f('LiteLLM_SpendLogs_session_id_idx'), 'LiteLLM_SpendLogs', ['session_id'], unique=False)
    op.create_index(op.f('LiteLLM_SpendLogs_end_user_idx'), 'LiteLLM_SpendLogs', ['end_user'], unique=False)
    op.create_table('LiteLLM_ManagedObjectTable',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unified_object_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_object_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_object', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('file_purpose', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('LiteLLM_ManagedObjectTable_pkey'))
    )
    op.create_index(op.f('LiteLLM_ManagedObjectTable_unified_object_id_key'), 'LiteLLM_ManagedObjectTable', ['unified_object_id'], unique=True)
    op.create_index(op.f('LiteLLM_ManagedObjectTable_unified_object_id_idx'), 'LiteLLM_ManagedObjectTable', ['unified_object_id'], unique=False)
    op.create_index(op.f('LiteLLM_ManagedObjectTable_model_object_id_key'), 'LiteLLM_ManagedObjectTable', ['model_object_id'], unique=True)
    op.create_index(op.f('LiteLLM_ManagedObjectTable_model_object_id_idx'), 'LiteLLM_ManagedObjectTable', ['model_object_id'], unique=False)
    op.create_table('LiteLLM_CredentialsTable',
    sa.Column('credential_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('credential_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('credential_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('credential_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('credential_id', name=op.f('LiteLLM_CredentialsTable_pkey'))
    )
    op.create_index(op.f('LiteLLM_CredentialsTable_credential_name_key'), 'LiteLLM_CredentialsTable', ['credential_name'], unique=True)
    op.create_table('LiteLLM_UserTable',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_alias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sso_user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_permission_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('teams', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('user_role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('models', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('max_parallel_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('budget_duration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget_reset_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('allowed_cache_controls', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('model_spend', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('model_max_budget', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['object_permission_id'], ['LiteLLM_ObjectPermissionTable.object_permission_id'], name='LiteLLM_UserTable_object_permission_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['LiteLLM_OrganizationTable.organization_id'], name='LiteLLM_UserTable_organization_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', name='LiteLLM_UserTable_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('LiteLLM_UserTable_sso_user_id_key'), 'LiteLLM_UserTable', ['sso_user_id'], unique=True)
    op.create_table('LiteLLM_OrganizationMembership',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('budget_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['LiteLLM_BudgetTable.budget_id'], name=op.f('LiteLLM_OrganizationMembership_budget_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['LiteLLM_OrganizationTable.organization_id'], name=op.f('LiteLLM_OrganizationMembership_organization_id_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['LiteLLM_UserTable.user_id'], name=op.f('LiteLLM_OrganizationMembership_user_id_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id', name=op.f('LiteLLM_OrganizationMembership_pkey'))
    )
    op.create_index(op.f('LiteLLM_OrganizationMembership_user_id_organization_id_key'), 'LiteLLM_OrganizationMembership', ['user_id', 'organization_id'], unique=True)
    op.create_table('LiteLLM_VerificationToken',
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_alias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('soft_budget_cooldown', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('models', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('max_parallel_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('max_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('budget_duration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget_reset_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('allowed_cache_controls', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('allowed_routes', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('model_spend', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('model_max_budget', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('budget_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_permission_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['LiteLLM_BudgetTable.budget_id'], name=op.f('LiteLLM_VerificationToken_budget_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_permission_id'], ['LiteLLM_ObjectPermissionTable.object_permission_id'], name=op.f('LiteLLM_VerificationToken_object_permission_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['LiteLLM_OrganizationTable.organization_id'], name=op.f('LiteLLM_VerificationToken_organization_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token', name=op.f('LiteLLM_VerificationToken_pkey'))
    )
    op.create_table('LiteLLM_TeamTable',
    sa.Column('team_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('team_alias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_permission_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admins', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('members', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('members_with_roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('max_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spend', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False),
    sa.Column('models', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('max_parallel_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rpm_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('budget_duration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget_reset_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('model_spend', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('model_max_budget', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('team_member_permissions', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['LiteLLM_ModelTable.id'], name=op.f('LiteLLM_TeamTable_model_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_permission_id'], ['LiteLLM_ObjectPermissionTable.object_permission_id'], name=op.f('LiteLLM_TeamTable_object_permission_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['LiteLLM_OrganizationTable.organization_id'], name=op.f('LiteLLM_TeamTable_organization_id_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('team_id', name=op.f('LiteLLM_TeamTable_pkey'))
    )
    op.create_index(op.f('LiteLLM_TeamTable_model_id_key'), 'LiteLLM_TeamTable', ['model_id'], unique=True)
    op.create_table('LiteLLM_ManagedFileTable',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unified_file_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_object', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('model_mappings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('flat_model_file_ids', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('LiteLLM_ManagedFileTable_pkey'))
    )
    op.create_index(op.f('LiteLLM_ManagedFileTable_unified_file_id_key'), 'LiteLLM_ManagedFileTable', ['unified_file_id'], unique=True)
    op.create_index(op.f('LiteLLM_ManagedFileTable_unified_file_id_idx'), 'LiteLLM_ManagedFileTable', ['unified_file_id'], unique=False)
    op.create_table('LiteLLM_MCPServerTable',
    sa.Column('server_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('transport', sa.TEXT(), server_default=sa.text("'sse'::text"), autoincrement=False, nullable=False),
    sa.Column('spec_version', sa.TEXT(), server_default=sa.text("'2025-03-26'::text"), autoincrement=False, nullable=False),
    sa.Column('auth_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('server_id', name=op.f('LiteLLM_MCPServerTable_pkey'))
    )
    op.create_table('LiteLLM_Config',
    sa.Column('param_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('param_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('param_name', name=op.f('LiteLLM_Config_pkey'))
    )
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index('ix_message_thread_seq', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_prompts_slug'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
